services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      monitoring-network:
        ipv4_address: 172.16.238.11

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - .env
    networks:
      monitoring-network:
        ipv4_address: 172.16.238.12

networks:
  monitoring-network:
    name: monitoring-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
