services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=30d'
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

    env_file:
      - .env
    networks:
      - monitoring-network

  loki:
    image: grafana/loki:latest
    restart: unless-stopped
    container_name: loki
    ports:
      - 3100:3100
    volumes:
      - loki_data:/tmp/loki
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring-network

  alert_handler:
    build:
      context: alert_handler/
      dockerfile: Dockerfile
    container_name: alert_handler
    command: >
      bash -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8080"
    restart: on-failure
    env_file:
      - ./alert_handler/.env
    networks:
      - monitoring-network
    volumes:
      - ./alert_handler/app:/src/app

networks:
  monitoring-network:
    name: monitoring-network
    driver: bridge

volumes:
  grafana_data:
  prometheus_data:
  loki_data:
