global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app'
    scrape_interval: 15s
    static_configs:
      - targets: ['192.168.10.100:8001']
        labels:
          service: "test1"
      - targets: ['192.168.10.100:8002']
        labels:
          service: "test2"

  - job_name: 'node_exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['192.168.10.100:9100']
        labels:
          node: "node1"
      - targets: ['192.168.10.100:9100']
        labels:
          node: "node2"

  - job_name: 'proxy'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.10.100:9100']
        labels:
          node: "node1"
      - targets: ['192.168.10.100:9100']
        labels:
          node: "node2"

